import 'package:gestion_casiers/src/features/lockers/domain/domain.dart';

final lockers = <Locker>[
  const Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 121,
    responsable: 'JHI',
    studentId: null,
    deposit: 0,
    keyCount: 2,
    lockNumber: 45501,
    lockerCondition: LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 122,
    responsable: 'JHI',
    studentId: students[0].id,
    deposit: 20,
    keyCount: 2,
    lockNumber: 45502,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 123,
    responsable: 'JHI',
    studentId: students[1].id,
    deposit: 20,
    keyCount: 2,
    lockNumber: 45503,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 124,
    responsable: 'JHI',
    studentId: students[2].id,
    deposit: 20,
    keyCount: 2,
    lockNumber: 45504,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 125,
    responsable: 'JHI',
    studentId: students[3].id,
    deposit: 20,
    keyCount: 2,
    lockNumber: 45505,
    lockerCondition: const LockerCondition(true),
  ),
  const Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 126,
    responsable: 'JHI',
    studentId: null,
    deposit: 0,
    keyCount: 2,
    lockNumber: 45506,
    lockerCondition: LockerCondition(true),
  ),
  const Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 127,
    responsable: 'JHI',
    studentId: null,
    deposit: 0,
    keyCount: 2,
    lockNumber: 45507,
    lockerCondition: LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 128,
    responsable: 'JHI',
    studentId: students[4].id,
    deposit: 0,
    keyCount: 3,
    lockNumber: 45508,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 129,
    responsable: 'JHI',
    studentId: students[5].id,
    deposit: 20,
    keyCount: 3,
    lockNumber: 45509,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 130,
    responsable: 'JHI',
    studentId: students[6].id,
    deposit: 20,
    keyCount: 3,
    lockNumber: 45510,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 131,
    responsable: 'JHI',
    studentId: students[7].id,
    deposit: 20,
    keyCount: 3,
    lockNumber: 45511,
    lockerCondition: const LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 132,
    responsable: 'JHI',
    studentId: students[8].id,
    deposit: 20,
    keyCount: 2,
    lockNumber: 45512,
    lockerCondition: const LockerCondition(true),
  ),
  const Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 133,
    responsable: 'JHI',
    studentId: null,
    deposit: 0,
    keyCount: 2,
    lockNumber: 45513,
    lockerCondition: LockerCondition(true),
  ),
  Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 134,
    responsable: 'JHI',
    studentId: students[9].id,
    deposit: 20,
    keyCount: 3,
    lockNumber: 45514,
    lockerCondition: const LockerCondition(true),
  ),
];

const students = <Student>[
  Student(
    id: '#Idtest1',
    firstName: 'Mafille',
    lastName: 'Quentin',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest2',
    firstName: 'Pozner',
    lastName: 'Quentin Darius',
    job: 'ICH-2022',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest3',
    firstName: 'Martinez',
    lastName: 'Enrique',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest4',
    firstName: 'Murad',
    lastName: 'Rayan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest5',
    firstName: 'Friedli',
    lastName: 'Robin Marius',
    job: 'ICH-2021',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest6',
    firstName: 'Stilli',
    lastName: 'William Thibaut',
    job: 'ICH-2022',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest7',
    firstName: 'Soares Oliveira',
    lastName: 'Diogo Filipe',
    job: 'ICH-2022',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest8',
    firstName: 'Brun',
    lastName: 'Sébastien',
    job: 'ICT-2020',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest9',
    firstName: 'Gagnebin',
    lastName: 'Eliot',
    job: 'ICH-2021',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  Student(
    id: '#Idtest10',
    firstName: 'Nuñez Mendez',
    lastName: 'Ivan',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
];
