import 'package:gestion_casiers/src/features/lockers/domain/domain.dart';

final lockers = <Locker>[
  const Locker(
    // place: 'Ancien Bâtiment',
    floor: 'c',
    number: 121,
    responsable: 'JHI',
    studentId: null,
    deposit: 0,
    keyCount: 2,
    lockNumber: 45501,
    lockerCondition: LockerCondition(true),
  ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 122,
  //     responsible: 'JHI',
  //     student: students[0],
  //     caution: 20,
  //     numberKeys: 2,
  //     lockerNumber: 45502,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 123,
  //     responsible: 'JHI',
  //     student: students[1],
  //     caution: 20,
  //     numberKeys: 2,
  //     lockerNumber: 45503,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 124,
  //     responsible: 'JHI',
  //     student: students[2],
  //     caution: 20,
  //     numberKeys: 2,
  //     lockerNumber: 45504,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 125,
  //     responsible: 'JHI',
  //     student: students[3],
  //     caution: 20,
  //     numberKeys: 2,
  //     lockerNumber: 45505,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 126,
  //     responsible: 'JHI',
  //     student: null,
  //     caution: 0,
  //     numberKeys: 2,
  //     lockerNumber: 45506,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 127,
  //     responsible: 'JHI',
  //     student: null,
  //     caution: 0,
  //     numberKeys: 2,
  //     lockerNumber: 45507,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 128,
  //     responsible: 'JHI',
  //     student: students[4],
  //     caution: 0,
  //     numberKeys: 3,
  //     lockerNumber: 45508,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 129,
  //     responsible: 'JHI',
  //     student: students[5],
  //     caution: 20,
  //     numberKeys: 3,
  //     lockerNumber: 45509,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 130,
  //     responsible: 'JHI',
  //     student: students[6],
  //     caution: 20,
  //     numberKeys: 3,
  //     lockerNumber: 45510,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 131,
  //     responsible: 'JHI',
  //     student: students[7],
  //     caution: 20,
  //     numberKeys: 3,
  //     lockerNumber: 45511,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 132,
  //     responsible: 'JHI',
  //     student: students[8],
  //     caution: 20,
  //     numberKeys: 2,
  //     lockerNumber: 45512,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 133,
  //     responsible: 'JHI',
  //     student: null,
  //     caution: 0,
  //     numberKeys: 2,
  //     lockerNumber: 45513,
  //   ),
  //   Locker(
  //     place: 'Ancien Bâtiment',
  //     floor: 'c',
  //     number: 134,
  //     responsible: 'JHI',
  //     student: students[9],
  //     caution: 20,
  //     numberKeys: 3,
  //     lockerNumber: 45514,
  //   ),
];

const students = <Student>[
  Student(
    id: '#Idtest1',
    firstName: 'Mafille',
    lastName: 'Quentin',
    job: 'ICT-2023',
    login: '',
    year: 0,
    title: '',
  ),
  // Student(
  //   id: '#Idtest2',
  //   name: 'Pozner',
  //   surname: 'Quentin Darius',
  //   job: 'ICH-2022',
  // ),
  // Student(
  //   id: '#Idtest3',
  //   name: 'Martinez',
  //   surname: 'Enrique',
  //   job: 'ICT-2023',
  // ),
  // Student(id: '#Idtest4', name: 'Murad', surname: 'Rayan', job: 'ICT-2023'),
  // Student(
  //   id: '#Idtest5',
  //   name: 'Friedli',
  //   surname: 'Robin Marius',
  //   job: 'ICH-2021',
  // ),
  // Student(
  //   id: '#Idtest6',
  //   name: 'Stilli',
  //   surname: 'William Thibaut',
  //   job: 'ICH-2022',
  // ),
  // Student(
  //   id: '#Idtest7',
  //   name: 'Soares Oliveira',
  //   surname: 'Diogo Filipe',
  //   job: 'ICH-2022',
  // ),
  // Student(id: '#Idtest8', name: 'Brun', surname: 'Sébastien', job: 'ICT-2020'),
  // Student(id: '#Idtest9', name: 'Gagnebin', surname: 'Eliot', job: 'ICH-2021'),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
  // Student(
  //   id: '#Idtest10',
  //   name: 'Nuñez Mendez',
  //   surname: 'Ivan',
  //   job: 'ICT-2023',
  // ),
];
